-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 02:16:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `autor` VARCHAR(100) NULL,
  `ISBN` INT NULL,
  `sinopsis` VARCHAR(400) NULL,
  `idioma` VARCHAR(50) NULL,
  `fechaDePublicacion` DATE NULL,
  `estado` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chat` (
  `idChat` INT NOT NULL AUTO_INCREMENT,
  `fechaDeCreacion` DATE NULL,
  PRIMARY KEY (`idChat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Usuario` (
  `idTipo_Usuario` INT NOT NULL AUTO_INCREMENT,
  `tipoDeUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comerciante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comerciante` (
  `idComerciante` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Usuario_idTipo_Usuario` INT NOT NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidoPaterno` VARCHAR(45) NULL,
  `apellidoMaterno` VARCHAR(45) NULL,
  `matricula` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idComerciante`, `Tipo_Usuario_idTipo_Usuario`),
  CONSTRAINT `fk_Comerciante_Tipo_Usuario1`
    FOREIGN KEY (`Tipo_Usuario_idTipo_Usuario`)
    REFERENCES `mydb`.`Tipo_Usuario` (`idTipo_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensaje` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `Chat_idChat` INT NOT NULL,
  `Comerciante_idComerciante` INT NOT NULL,
  `contenidoMensaje` VARCHAR(200) NULL,
  `marcaDeTiempo` DATE NULL,
  PRIMARY KEY (`idMensaje`, `Chat_idChat`, `Comerciante_idComerciante`),
  CONSTRAINT `fk_Mensaje_Chat1`
    FOREIGN KEY (`Chat_idChat`)
    REFERENCES `mydb`.`Chat` (`idChat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensaje_Comerciante1`
    FOREIGN KEY (`Comerciante_idComerciante`)
    REFERENCES `mydb`.`Comerciante` (`idComerciante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `Comerciante_idComerciante` INT NOT NULL,
  `Comerciante_idComercianteDeComentario` INT NOT NULL,
  `titulo` VARCHAR(50) NULL,
  `descripcion` VARCHAR(300) NULL,
  PRIMARY KEY (`idComentario`, `Comerciante_idComerciante`, `Comerciante_idComercianteDeComentario`),
  CONSTRAINT `fk_Comentario_Comerciante1`
    FOREIGN KEY (`Comerciante_idComercianteDeComentario`)
    REFERENCES `mydb`.`Comerciante` (`idComerciante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Comerciante2`
    FOREIGN KEY (`Comerciante_idComerciante`)
    REFERENCES `mydb`.`Comerciante` (`idComerciante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Intercambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Intercambio` (
  `idIntercambio` INT NOT NULL AUTO_INCREMENT,
  `Comerciante_idComerciante` INT NOT NULL,
  `Libro_idLibro` INT NOT NULL,
  `fechaDeCreacion` DATE NULL,
  `fechaDeFinalizacion` DATE NULL,
  PRIMARY KEY (`idIntercambio`, `Comerciante_idComerciante`, `Libro_idLibro`),
  CONSTRAINT `fk_Intercambio_Comerciante1`
    FOREIGN KEY (`Comerciante_idComerciante`)
    REFERENCES `mydb`.`Comerciante` (`idComerciante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Intercambio_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `mydb`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comerciante_Con_Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comerciante_Con_Chat` (
  `Chat_idChat` INT NOT NULL,
  `Comerciante_idComerciante` INT NOT NULL,
  PRIMARY KEY (`Chat_idChat`, `Comerciante_idComerciante`),
  CONSTRAINT `fk_Chat_has_Comerciante_Chat1`
    FOREIGN KEY (`Chat_idChat`)
    REFERENCES `mydb`.`Chat` (`idChat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chat_has_Comerciante_Comerciante1`
    FOREIGN KEY (`Comerciante_idComerciante`)
    REFERENCES `mydb`.`Comerciante` (`idComerciante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
